# See http://www.appveyor.com/docs/appveyor-yml for many more options


image:
  - Visual Studio 2013 # Windows - PowerShell 5.1
  - Visual Studio 2022 # Windows - PowerShell 7
  - Ubuntu # Linux - PowerShell 7

# Skip on updates to the readme, doc, package in the commit message.
skip_commits:
  message: /updated (package|readme|doc).*|update (package|readme|doc).*s/

#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1 -Task Default
  - pwsh: . .\build.ps1 -Task Default
build: false